import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "./providers/query-provider";
import SingleColumnLayout from "@/components/layout/SingleLayout";

const pretandard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretandard",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretandard.variable} antialiased `}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <SingleColumnLayout>{children}</SingleColumnLayout>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
