import type { Metadata } from "next";
import localFont from "next/font/local";

import { ThemeProvider } from "@/lib/providers/theme-provider";
import QueryProvider from "@/lib/providers/query-provider";
import SingleColumnLayout from "@/components/layout/SingleLayout";
import "./globals.css";

const pretandard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretandard",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="kr"
      suppressHydrationWarning
      className={`${pretandard.variable} antialiased `}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <SingleColumnLayout>{children}</SingleColumnLayout>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
